#!/usr/bin/env python3
"""Generate the two install bundles from the flat skills/ tree.

The source of truth is `skills/<name>/SKILL.md`. Bundle membership is derived
from `requires:` — no separate list to maintain and drift:

  core          requires: []  or only external:*   — works on a bare repo or with
                public services only. Ships the crew roles and templates too.
  capabilities  requires: mcp:* or cluster         — needs infrastructure the
                consumer runs (a federated MCP gateway, a live cluster).

Each bundle is a self-contained, install-ready tree, so every harness can point
at a directory: Claude Code at a plugin dir, pi at a package path, Codex and
OpenClaw at a skills dir for their copy loops.

Usage:
  scripts/gen_bundles.py           # write bundles/
  scripts/gen_bundles.py --check   # exit 1 if bundles/ is stale (CI)
"""

import json
import pathlib
import shutil
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
BUNDLES = ROOT / "bundles"
NOTICE = "GENERATED by scripts/gen_bundles.py — do not edit; edit the source tree and re-run."


def yaml_module():
    try:
        import yaml
    except ImportError:
        import subprocess

        subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", "pyyaml"])
        import yaml
    return yaml


def bundle_of(requires):
    """core unless the skill needs infrastructure the consumer has to run."""
    if not requires:
        return "core"
    return "core" if all(r.startswith("external:") for r in requires) else "capabilities"


def classify():
    yaml = yaml_module()
    out = {"core": [], "capabilities": []}
    for path in sorted(ROOT.glob("skills/*/SKILL.md")):
        fm = yaml.safe_load(path.read_text().split("---", 2)[1])
        out[bundle_of(fm["requires"])].append(path.parent)
    return out


def build(dest: pathlib.Path, name: str, description: str, skills, extras):
    """Materialise one bundle tree into dest."""
    dest.mkdir(parents=True)
    (dest / "README.md").write_text(f"<!-- {NOTICE} -->\n\n# {name}\n\n{description}\n")
    (dest / ".claude-plugin").mkdir()
    version = json.loads((ROOT / ".claude-plugin/plugin.json").read_text())["version"]
    (dest / ".claude-plugin/plugin.json").write_text(
        json.dumps(
            {
                "name": name,
                "description": description,
                "version": version,
                "author": {"name": "ductiletoaster"},
                "repository": "https://github.com/ductiletoaster/harmony-crew",
                "license": "MIT",
            },
            indent=2,
            ensure_ascii=False,
        )
        + "\n"
    )
    skills_dir = dest / "skills"
    skills_dir.mkdir()
    for src in skills:
        shutil.copytree(src, skills_dir / src.name)
    for rel in extras:
        src = ROOT / rel
        shutil.copytree(src, dest / rel) if src.is_dir() else shutil.copy2(src, dest / rel)
    # a machine-readable membership list, same shape as slices/openclaw.txt
    (dest / "skills.txt").write_text("\n".join(sorted(s.name for s in skills)) + "\n")


def generate():
    if BUNDLES.exists():
        shutil.rmtree(BUNDLES)
    groups = classify()
    build(
        BUNDLES / "core",
        "harmony-crew-core",
        "Portable agent foundation: 8 crew roles, planning/review/orchestration disciplines, "
        "stack conventions, onboarding + doctor. Works on a bare repo — no platform required.",
        groups["core"],
        ["agents", "pi-agents", "templates"],
    )
    build(
        BUNDLES / "capabilities",
        "harmony-crew-capabilities",
        "Platform capability skills: knowledge base, web search, image generation, browser, "
        "code intelligence, dev workspaces, cluster ops, secrets, gateway routing. "
        "Requires the corresponding capabilities to be reachable — see each skill's `requires:`.",
        groups["capabilities"],
        [],
    )
    return {k: len(v) for k, v in groups.items()}


def main():
    check = "--check" in sys.argv
    if check:
        if not BUNDLES.exists():
            sys.exit("bundles/ missing — run scripts/gen_bundles.py and commit")
        import filecmp

        before = ROOT / ".bundles-check"
        if before.exists():
            shutil.rmtree(before)
        shutil.copytree(BUNDLES, before)
        counts = generate()
        diff = filecmp.dircmp(before, BUNDLES)

        def differs(d):
            if d.left_only or d.right_only or d.diff_files:
                return True
            return any(differs(sub) for sub in d.subdirs.values())

        stale = differs(diff)
        shutil.rmtree(before)
        if stale:
            sys.exit("bundles/ is out of date — run scripts/gen_bundles.py and commit")
        print(f"bundles current — core {counts['core']}, capabilities {counts['capabilities']}")
    else:
        counts = generate()
        print(f"wrote bundles/core ({counts['core']} skills) + bundles/capabilities ({counts['capabilities']} skills)")


if __name__ == "__main__":
    main()
