#!/usr/bin/env python3
"""Generate the machine-readable artifacts derived from SKILL.md frontmatter:

  slices/openclaw.txt   the OpenClaw consumption slice — every skill whose
                        audience includes 'persona', one name per line. The
                        README's gateway init-skills snippet consumes this
                        file directly, so the slice can never drift from
                        frontmatter again.
  docs/CATALOG.md       browsable inventory of the full catalog.

Usage:
  scripts/gen_catalog.py           # write both artifacts
  scripts/gen_catalog.py --check   # exit 1 if either is out of date (CI)
"""

import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent


def yaml_module():
    try:
        import yaml
    except ImportError:
        import subprocess

        subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", "pyyaml"])
        import yaml
    return yaml


def load_skills():
    yaml = yaml_module()
    skills = []
    for path in sorted(ROOT.glob("skills/*/SKILL.md")):
        fm = yaml.safe_load(path.read_text().split("---", 2)[1])
        skills.append(fm)
    return skills


def render_slice(skills):
    names = [s["name"] for s in skills if "persona" in s.get("audience", [])]
    return "\n".join(names) + "\n"


CAPABILITY_LABEL = {
    "cluster": "Cluster access",
    "external:github": "GitHub",
    "external:web": "Web access",
    "mcp:kb": "Knowledge base",
    "mcp:search": "Web search",
    "mcp:imagegen": "Image generation",
    "mcp:browser": "Browser",
    "mcp:codeintel": "Code intelligence",
    "mcp:coder": "Dev workspaces",
}


def render_index(skills):
    """The agent-facing skill index — a generated SKILL.md.

    Roles carry no skill lists; they consult this. Grouping is by capability
    requirement so an agent can skip whole sections it cannot reach, and the
    descriptions carry the task-matching signal.
    """
    groups = {}
    for s in skills:
        key = ", ".join(CAPABILITY_LABEL.get(r, r) for r in s["requires"]) or None
        groups.setdefault(key, []).append(s)

    lines = [
        "---",
        "name: skill-index",
        "description: The catalogue of every available skill, grouped by the platform capability it needs, "
        "with each skill's trigger description. Consult this when choosing which skill to load for a task — "
        "it is the map; individual role definitions deliberately carry no skill lists. Load it early in any "
        "non-trivial task, and re-consult it whenever the work moves into a new domain.",
        "tier: concept",
        "requires: []",
        "audience: [crew]",
        "---",
        "",
        "<!-- GENERATED by scripts/gen_catalog.py from SKILL.md frontmatter — do not edit -->",
        "",
        "# Skill index",
        "",
        "Every skill available in this catalogue. **Match your task against the descriptions and load what fits** —",
        "loading a skill is cheap, re-deriving its conventions is not.",
        "",
        "Sections below the first name a **platform capability**. If your deployment cannot reach that capability,",
        "the skills under it will not help you: skip the section, and if a task needs one, say the capability is",
        "unavailable rather than improvising a substitute. Run the `doctor` skill if you are unsure what is reachable.",
        "",
        "## Always available (no platform capability required)",
        "",
    ]
    for s in sorted(groups.pop(None, []), key=lambda x: x["name"]):
        lines.append(f"- **`{s['name']}`** — {s['description']}")
    for key in sorted(groups):
        lines += ["", f"## Requires: {key}", ""]
        for s in sorted(groups[key], key=lambda x: x["name"]):
            lines.append(f"- **`{s['name']}`** — {s['description']}")
    lines += [
        "",
        "## Consumer-local skills",
        "",
        "A project supplies its own skills for its specifics (topology, conventions, protected seams, access maps).",
        "Those are **not** listed here — they live in the project's overlay and resolve by name, shadowing a",
        "foundation skill where the names collide. The project's `AGENTS.md` indexes them.",
        "",
    ]
    return "\n".join(lines)


def render_catalog(skills):
    lines = [
        "<!-- GENERATED by scripts/gen_catalog.py from SKILL.md frontmatter — do not edit -->",
        "",
        "# Skill catalog",
        "",
        f"{len(skills)} skills. `requires` legend: empty = portable (bare repo); `mcp:<group>` = needs that",
        "federated MCP capability on the consumer's virtual key; `cluster` = needs live cluster/platform",
        "access; `external:*` = needs a public platform. `audience` containing `persona` = part of the",
        "OpenClaw consumption slice (`slices/openclaw.txt`).",
        "",
        "| Skill | Tier | Requires | Audience | Expects local | Description |",
        "|---|---|---|---|---|---|",
    ]
    for s in skills:
        req = ", ".join(s["requires"]) if s["requires"] else "—"
        aud = ", ".join(s["audience"])
        slots = ", ".join(s.get("expects-local", [])) or "—"
        desc = s["description"].replace("|", "\\|")
        lines.append(f"| `{s['name']}` | {s['tier']} | {req} | {aud} | {slots} | {desc} |")
    return "\n".join(lines) + "\n"


def main():
    check = "--check" in sys.argv
    skills = load_skills()
    outputs = {
        ROOT / "slices" / "openclaw.txt": render_slice(skills),
        ROOT / "docs" / "CATALOG.md": render_catalog(skills),
        ROOT / "skills" / "skill-index" / "SKILL.md": render_index(skills),
    }
    stale = []
    for path, content in outputs.items():
        current = path.read_text() if path.exists() else None
        if current == content:
            continue
        if check:
            stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(exist_ok=True)
            path.write_text(content)
            print(f"wrote {path.relative_to(ROOT)}")
    if check:
        if stale:
            print("generated artifacts out of date — run scripts/gen_catalog.py and commit:")
            print("\n".join(f"  {s}" for s in stale))
            sys.exit(1)
        print("slices/openclaw.txt and docs/CATALOG.md are current")


if __name__ == "__main__":
    main()
